# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

exclude: 'docs/doxygen/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.1.6
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx|js|proto)$
        args: ["-i"]
      - id: cpplint
        name: cpplint
        entry: cpplint
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args:
          - --recursive
